server:
  port: 8080

spring:
  # profiles:
  #  active: native
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: "{cipher}c8fb983068048206ccd0170aeafa620d2eda867aad4e2971e68be66abe12dd39"
    password: "{cipher}c8fb983068048206ccd0170aeafa620d2eda867aad4e2971e68be66abe12dd39"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

info:
  app:
    name: "auth-service"
    description: "JobHunter Auth Application"
    version: "1.0"
